= Blog (work in progress)

My personal blog, hosted at https://oli.me.uk/[oli.me.uk]. Written in https://clojure.org/[Clojure] using https://github.com/Olical/conjure[Conjure] and https://neovim.io/[Neovim].

It's a static site rendered from http://asciidoc.org/[AsciiDoc], feel free to copy and modify the code if you think you'll find it useful!

== Tools

 * `make build` - Render the blog to static HTML in `output`.
 * `make propel` - Start a prepl server with https://github.com/Olical/propel[Propel] and write the port to `.prepl-port`.
 * `make depot` - Check for outdated dependencies with https://github.com/Olical/depot[Depot].
 * `make test` - Execute all of the tests.
 * `make serve` - Host the `output` directory with Python's `http.server` module.
 * `make watch` - Rebuild when any source files change, requires http://eradman.com/entrproject/[entr] to be installed and `make propel` already running.
 * `make build-container` - Build the docker container and tag it as `blog`.
 * `make run-container` - Run the container locally, hosts on port `8080`.
 * `make setup-deploy` - Configures git to deploy to my host.
 * `make deploy` - Deploys the current master to my host.

== Hosting

This blog runs on https://m.do.co/c/e643aa564b21[Digital Ocean] (referral link!) via http://dokku.viewdocs.io/dokku/[Dokku].

== Unlicenced

The posts are mine and you should not republish them without asking permission or attribution, the code is fair game.

Find the full http://unlicense.org/[unlicense] in the `UNLICENSE` file, but here's a snippet.

____
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
____
