= Blog

My personal blog, hosted at https://oli.me.uk/[oli.me.uk]. Written in https://clojure.org/[Clojure] using https://github.com/Olical/conjure[Conjure] and https://neovim.io/[Neovim].

It's a static site rendered from http://asciidoc.org/[AsciiDoc], feel free to copy and modify the code if you think you'll find it useful!

== Tools

 * `make build` - Render the blog to static HTML in `output`.
 * `make propel` - Start a prepl server with https://github.com/Olical/propel[Propel] and write the port to `.prepl-port`.
 * `make depot` - Check for outdated dependencies with https://github.com/Olical/depot[Depot].
 * `make test` - Execute all of the tests.
 * `make serve` - Host the `output` directory with Python's `http.server` module.
 * `make watch` - Rebuild when any source files change, requires http://eradman.com/entrproject/[entr] to be installed and `make propel` already running.
 * `make build-container` - Build the docker container and tag it as `blog`.
 * `make run-container` - Run the container locally, hosts on port `9898`.
 * `make setup-deploy` - Configures git to deploy to my host.
 * `make deploy` - Deploys the current master to my host.

== Hosting

This blog runs on https://fly.io/[fly.io] (referral link!)

The container ends up being just the static rendered HTML served by https://www.nginx.com/[nginx] hosted in Dokku. The `server` directory contains the nginx configuration template, the `$PORT` that Dokku selects is added in at startup.

== Forking

Feel free to fork this project and adapt it for your own needs! You'll need to replace my domain in a few places (`oli.me.uk`) as well as my name. I'd prefer you to delete my posts and write your own too...

You'll probably want to edit the nginx configuration to remove the redirects I added for my own legacy blog reasons as well.

Just have a look around the source and grep for some things you spot that are related to myself, feel free to do whatever you'd like with the code.

If you get a lot out of forking this project I'd love to hear about it.

== Unlicenced

The posts are mine and you should not republish them without asking permission or attribution, the code is fair game.

Find the full http://unlicense.org/[unlicense] in the `UNLICENSE` file, but here's a snippet.

____
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
____
