= Always remain a beginner
Oliver Caldwell
2014-03-18

I’ve been programming for about five years, almost entirely in JavaScript, three of which being professional. I’m an absolute beginner and I always will be. This is a _good_ thing.

=== Why remain a beginner?

Because a beginner will never stop learning. A beginner must continually progress or they will stall in their learning, stalling brings with it unhappiness and resentment towards your current situation.

Beginners actively seek knowledge and cast away presumptions, even if they think they know all there is to know about a given technology.

=== They listen

It’s not just the desire to learn from books or blogs however, a beginner will also appreciate the knowledge of friends and colleagues; they _will_ listen when someone says something of interest directly to them.

This is out of respect as much as a thirst for knowledge, it shows that you appreciate their input and accept that you could easily be very wrong in your assumptions. The only fair assumption is that they know more than you until _proven otherwise_. (See: https://www.youtube.com/watch?v=wg4trPZFUwc[Assumption is the mother of all fuck-ups])

=== Growing causes happiness

Growth makes people happy, as mentioned in http://www.gretchenrubin.com/books/the-happiness-project/about-the-book/[The Happiness Project], an excellent book (that I heard of through http://www.raptitude.com/[raptitude]) that I’m still working my way through. A beginner will be happy while they learn, so never stop learning. Never slip into an elitist attitude, you do not _know_ anything completely, you should listen to those who speak with conviction.

Never stop learning and growing. This will bring you joy and respect among your peers. This works for me especially so due to my passion for acquiring new knowledge.

If you realise that you’ve stopped growing for even a single day, *do something about it*.

=== There is always something to learn

Regardless of what you may think, you still have much to learn. Never, not even for one second, should you slip into the mentality in which you think you know something wholly and completely.

At this point, you cease listening to reason and instead dictate your opinions as fact, which can be easy to do in the heat of a conversation. This is extremely counter-productive.

=== There’s a fine line

And you must tread it carefully. Sometimes an assertion of your opinion is required to sway some individuals, but most of the time a two way conversation will be far more useful.

Discuss, don’t tell. But what’re you listening to me for? What do I know? I’m but a beginner.

This can also be construed as paradoxical.
