= Hello again, WordPress
Oliver Caldwell
2014-08-06

Once again I’m reworking my personal website and blog. This time I’m aiming to journal my progress through projects that I work on in my free time (such as https://github.com/Wolfy87/vim-enmasse[Vim plugins]) as well as the odd rant or tutorial post, as I have written in the past. I felt that trying to force myself to write large posts about huge topics and problems on a regular basis was just too difficult to keep up with in those precious few hours I have during some evenings. So my new goal is to journal my progress through my personal projects which should show other hows I work (sort of) and potentially teach other developers some neat tricks I didn’t realise were that neat.

I’ve decided to drop back to https://wordpress.org/[WordPress], which I think is the third flip between a static (http://octopress.org/[Octopress]) and WordPress powered blog, which I am very happy with. http://scotthsmith.com/projects/decode/[The theme] is brilliant and amazingly configurable, https://www.cloudflare.com/[CloudFlare] is optimising the hell out of it and I have a few plugins managing security enhancements and SEO tweaks on my behalf. Setting up the install through my host, http://webfaction.com/[WebFaction], was painless and smooth, I couldn’t be happier really.

I hope to have many years of use out of my current set-up which will provide fresh insight and knowledge for as many developer as possible.

Here we go again…
