= I want to learn stuff and write about it over 2015
Oliver Caldwell
2014-12-10

I mean, I’ve been doing that on and (mostly) off for a while now, but I really want to focus on things like https://www.khanacademy.org/[Khan Academy] (which I’m currently using to learn more about algorithms). So hopefully you’ll see more frequent, yet short, posts on things I’ve recently stumbled across. I’ll try and write a few in batches and space them out evenly to make it a little less sporadic.

I’m also looking to write way more Vim plugins and experimental “Hello, World!”-ish applications with novel technologies such as http://facebook.github.io/react/[React] and https://github.com/clojure/clojurescript[ClojureScript].

I know this is a tiny and nigh on pointless post, but I felt that I had to put my intentions in words to put more weight behind it. My motivation will be acquisition knowledge and hopefully sharing it. Now I’m going to work on my second ever Vim plugin and a couple of little posts.
